version: "3.9"
services:
  adb:
    build: ./
    image: "chomupashchuk/custom-adb:1.3"
    container_name: "adb"
    ports:
      - "5037:5037"
    environment:
      - TV_IPS="192.168.1.111 192.168.1.112"
